// <auto-generated />
using System;
using System.Collections.Generic;
using Imobi.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Imobi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251015183540_AddUnidadeId2Arquivo")]
    partial class AddUnidadeId2Arquivo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Imobi.Models.Arquivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Caminho")
                        .HasColumnType("text");

                    b.Property<int>("EmpreendimentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Extensao")
                        .HasColumnType("text");

                    b.Property<string>("NomeArquivo")
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpreendimentoId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Arquivos");
                });

            modelBuilder.Entity("Imobi.Models.Condominio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArquivoId")
                        .HasColumnType("integer");

                    b.Property<Guid>("EmpreendimentoId")
                        .HasColumnType("uuid");

                    b.Property<int?>("EmpreendimentoId1")
                        .HasColumnType("integer");

                    b.Property<int>("InstalacoesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArquivoId");

                    b.HasIndex("EmpreendimentoId1");

                    b.HasIndex("InstalacoesId");

                    b.ToTable("Condominios");
                });

            modelBuilder.Entity("Imobi.Models.Empreendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaConstruida")
                        .HasColumnType("text");

                    b.Property<int>("ArquivoId")
                        .HasColumnType("integer");

                    b.Property<int?>("BanheirosTotal")
                        .HasColumnType("integer");

                    b.Property<int?>("DormitoriosTotal")
                        .HasColumnType("integer");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estagio")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Sobre")
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<int?>("SuitesTotal")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("integer");

                    b.Property<int?>("VagasTotal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Empreendimentos");
                });

            modelBuilder.Entity("Imobi.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Logradouro")
                        .HasColumnType("text");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<string>("Uf")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("Imobi.Models.InstalacaoCondominio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("Recursos")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("InstalacaoCondominios");
                });

            modelBuilder.Entity("Imobi.Models.Unidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaConstruida")
                        .HasColumnType("integer");

                    b.Property<int>("ArquivoId")
                        .HasColumnType("integer");

                    b.Property<int>("Banheiros")
                        .HasColumnType("integer");

                    b.Property<int>("Dormitorios")
                        .HasColumnType("integer");

                    b.Property<int>("EmpreendimentoId")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<int>("Suites")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.Property<int>("Vagas")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("EmpreendimentoId");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("Imobi.Models.Arquivo", b =>
                {
                    b.HasOne("Imobi.Models.Empreendimento", null)
                        .WithMany("Arquivos")
                        .HasForeignKey("EmpreendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Imobi.Models.Unidade", null)
                        .WithMany("Arquivos")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Imobi.Models.Condominio", b =>
                {
                    b.HasOne("Imobi.Models.Arquivo", "Arquivo")
                        .WithMany()
                        .HasForeignKey("ArquivoId");

                    b.HasOne("Imobi.Models.Empreendimento", "Empreendimento")
                        .WithMany()
                        .HasForeignKey("EmpreendimentoId1");

                    b.HasOne("Imobi.Models.InstalacaoCondominio", "Instalacoes")
                        .WithMany()
                        .HasForeignKey("InstalacoesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arquivo");

                    b.Navigation("Empreendimento");

                    b.Navigation("Instalacoes");
                });

            modelBuilder.Entity("Imobi.Models.Empreendimento", b =>
                {
                    b.HasOne("Imobi.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Imobi.Models.Unidade", b =>
                {
                    b.HasOne("Imobi.Models.Empreendimento", "Empreendimento")
                        .WithMany("Unidades")
                        .HasForeignKey("EmpreendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empreendimento");
                });

            modelBuilder.Entity("Imobi.Models.Empreendimento", b =>
                {
                    b.Navigation("Arquivos");

                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("Imobi.Models.Unidade", b =>
                {
                    b.Navigation("Arquivos");
                });
#pragma warning restore 612, 618
        }
    }
}
